import { Course, Quiz, Certificate, LiveSession, CommunityPost } from "@/types";

export const INSTRUCTOR_PROFILE = {
  id: "inst-1",
  name: "Rahul Kamat",
  title: "Founder & Lead SDET Mentor",
  experience: "17+ Years in Software Testing & Automation",
  organization: "NextGen Testing Academy (NGTA)",
  avatarUrl: "/instructor/rahul-kamat.png",
  totalStudents: "10,000+",
  reviewsCount: "1,840+",
  rating: 4.9,
  coursesCount: 4,
  headline: "17+ Years QA Leader | Architecting Automation Solutions & Training High-Velocity SDETs",
  bio: "Rahul Kamat is an experienced software testing leader with over 17 years of hands-on expertise architecting enterprise automation frameworks and mentoring thousands of QA professionals. As the founder and lead instructor at NextGen Testing Academy (NGTA), he specializes in transforming manual testers into career-ready SDETs through real-world projects, CI/CD mastery, and cutting-edge AI-powered testing.",
  skills: [
    "Selenium 4 WebDriver",
    "Java OOP from Scratch",
    "AI-Powered Testing",
    "Self-Healing Locators",
    "Page Object Model (POM)",
    "TestNG & Maven",
    "Jenkins CI/CD",
    "Playwright & TypeScript",
  ],
};

export const INITIAL_COURSES: Course[] = [
  {
    id: "course-1",
    slug: "selenium-automation-masterclass",
    title: "Selenium Java + AI: Complete Automation Testing Course",
    subtitle: "From Zero to Automation Pro: Master Selenium 4, Java, TestNG, Jenkins CI/CD & Cutting-Edge AI Testing Tools",
    description: "Architect production-grade test automation frameworks from the ground up. Master Java with no prior coding experience required, build scalable Page Object Model (POM) architectures with TestNG and Maven, integrate automated CI/CD pipelines in Jenkins, and leverage modern AI tools for self-healing locators and automated test case generation.",
    instructorId: "inst-1",
    instructorName: "Rahul Kamat",
    instructorTitle: "Lead SDET & Founder @ NextGen Testing Academy (17+ Yrs Exp)",
    instructorAvatarUrl: "/instructor/rahul-kamat.png",
    instructorBio: "Rahul Kamat is a senior automation architect with over 17 years in QA leadership. Founder of NextGen Testing Academy (NGTA), mentoring over 10,000+ SDETs worldwide.",
    category: "Automation Testing",
    tags: ["Selenium 4", "Java", "AI Testing", "TestNG", "Jenkins CI/CD", "Self-Healing Locators"],
    thumbnailUrl: "/courses/selenium-java-ai.jpg",
    bannerUrl: "/courses/selenium-java-ai.jpg",
    difficultyLevel: "All Levels",
    durationHours: 25.5,
    priceINR: 4999,
    discountPriceINR: 1999,
    status: "PUBLISHED",
    rating: 4.9,
    ratingsCount: 1840,
    studentsCount: 10450,
    updatedAt: "2026-03-20",
    objectives: [
      "Master Core Java from scratch with OOP principles tailored specifically for test automation",
      "Architect a robust Page Object Model (POM) and Hybrid Framework using Selenium 4 & TestNG",
      "Integrate modern AI tools for self-healing locators to prevent fragile test suite breaks",
      "Auto-generate test cases and smart assertions from user stories using AI testing assistants",
      "Configure automated CI/CD execution with Jenkins, Maven, and Git pipelines",
      "Execute parallel, cross-browser test suites with ThreadLocal driver management",
    ],
    prerequisites: [
      "No prior coding experience required — Java is taught from absolute scratch",
      "Basic familiarity with web browsers and manual testing concepts",
    ],
    targetAudience: [
      "Manual QA testers aiming to transition into high-paying SDET and automation roles",
      "Freshers and engineering graduates looking to build a job-ready test automation portfolio",
      "Experienced QA engineers seeking to modernize their skill set with AI-powered testing",
    ],
    modules: [
      {
        id: "mod-1",
        courseId: "course-1",
        title: "Module 01: Java Fundamentals from Scratch for Automation",
        order: 1,
        chapters: [
          {
            id: "chap-1-1",
            moduleId: "mod-1",
            title: "Java Basics & OOP Architecture",
            order: 1,
            lessons: [
              {
                id: "les-1",
                chapterId: "chap-1-1",
                title: "Java Environment Setup (JDK 21) & First Program",
                order: 1,
                durationMinutes: 20,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Complete guide to installing Java JDK, configuring environment variables, setting up Eclipse / IntelliJ IDEA, and understanding JVM execution.",
              },
              {
                id: "les-2",
                chapterId: "chap-1-1",
                title: "OOP Essentials: Classes, Objects, Inheritance & Encapsulation",
                order: 2,
                durationMinutes: 35,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Learn how OOP concepts form the foundation of test automation frameworks with practical hands-on examples.",
              },
            ],
          },
        ],
      },
      {
        id: "mod-2",
        courseId: "course-1",
        title: "Module 02: Selenium 4 WebDriver & Dynamic Locators",
        order: 2,
        chapters: [
          {
            id: "chap-2-1",
            moduleId: "mod-2",
            title: "WebDriver Architecture & Resilient Selectors",
            order: 1,
            lessons: [
              {
                id: "les-3",
                chapterId: "chap-2-1",
                title: "Selenium 4 Architecture & W3C Standard Driver Setup",
                order: 1,
                durationMinutes: 28,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Deep dive into Selenium 4 architecture, driver managers, Chromium / Firefox automation, and browser options.",
              },
              {
                id: "les-4",
                chapterId: "chap-2-1",
                title: "Mastering Complex Dynamic XPath & CSS Selectors",
                order: 2,
                durationMinutes: 30,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Craft bulletproof XPath queries with following-sibling, ancestor, preceding axes, and regex for dynamic web apps.",
              },
            ],
          },
        ],
      },
      {
        id: "mod-3",
        courseId: "course-1",
        title: "Module 03: Page Object Model (POM) & TestNG Framework",
        order: 3,
        chapters: [
          {
            id: "chap-3-1",
            moduleId: "mod-3",
            title: "Enterprise Framework Design",
            order: 1,
            lessons: [
              {
                id: "les-5",
                chapterId: "chap-3-1",
                title: "Building POM Architecture & ThreadLocal Parallel Execution",
                order: 1,
                durationMinutes: 45,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Architect clean Page Object classes and implement thread-safe WebDriver instances using Java ThreadLocal in TestNG.",
              },
              {
                id: "les-6",
                chapterId: "chap-3-1",
                title: "Data-Driven Testing with Apache POI & Allure Reporting",
                order: 2,
                durationMinutes: 40,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Drive test parameters via Excel data sheets and auto-attach failure screenshots to rich HTML reporting dashboards.",
              },
            ],
          },
        ],
      },
      {
        id: "mod-4",
        courseId: "course-1",
        title: "Module 04: AI-Powered Automation & Self-Healing Locators",
        order: 4,
        chapters: [
          {
            id: "chap-4-1",
            moduleId: "mod-4",
            title: "NextGen AI Testing Integration",
            order: 1,
            lessons: [
              {
                id: "les-7",
                chapterId: "chap-4-1",
                title: "Implementing AI Self-Healing Locators in Selenium",
                order: 1,
                durationMinutes: 35,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Learn how to integrate AI self-healing mechanisms so test suites automatically adapt to DOM updates without breaking.",
              },
              {
                id: "les-8",
                chapterId: "chap-4-1",
                title: "AI-Driven Test Generation & Intelligent Reporting",
                order: 2,
                durationMinutes: 25,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Generate comprehensive test scenarios from product specifications and craft automated plain-English summary reports.",
              },
            ],
          },
        ],
      },
      {
        id: "mod-5",
        courseId: "course-1",
        title: "Module 05: Jenkins CI/CD & Certification Assessment",
        order: 5,
        chapters: [
          {
            id: "chap-5-1",
            moduleId: "mod-5",
            title: "Continuous Testing & Portfolio Project",
            order: 1,
            lessons: [
              {
                id: "les-9",
                chapterId: "chap-5-1",
                title: "Jenkins CI/CD Automation & GitHub Webhook Triggers",
                order: 1,
                durationMinutes: 35,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Trigger automated test suites on git commit, publish reports to Jenkins server, and configure automated email alerts.",
              },
              {
                id: "les-10",
                chapterId: "chap-5-1",
                title: "Assessment: Full-Stack SDET & AI Testing Certification Quiz",
                order: 2,
                durationMinutes: 20,
                type: "quiz",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "course-2",
    slug: "playwright-typescript-end-to-end",
    title: "NextGen Full-Stack QA & SDET Automation Masterclass",
    subtitle: "Complete QA Mastery: Manual Testing, API Validation, Database Verification, Playwright E2E & CI/CD Pipelines",
    description: "Architect comprehensive test strategies across the entire software delivery lifecycle. Designed by Rahul Kamat (17+ yrs experience), this course takes you through core QA principles, defect lifecycle management, REST API testing, SQL validation, modern browser automation with Playwright & TypeScript, and automated quality gates in CI/CD.",
    instructorId: "inst-1",
    instructorName: "Rahul Kamat",
    instructorTitle: "Lead SDET & Founder @ NextGen Testing Academy (17+ Yrs Exp)",
    instructorAvatarUrl: "/instructor/rahul-kamat.png",
    instructorBio: "Rahul Kamat is a senior automation architect with over 17 years in QA leadership. Founder of NextGen Testing Academy (NGTA), mentoring over 10,000+ SDETs worldwide.",
    category: "Full-Stack QA & SDET",
    tags: ["Manual QA", "API Testing", "Playwright", "Database Testing", "CI/CD", "Quality Gates"],
    thumbnailUrl: "/courses/sdet-automation-masterclass.jpg",
    bannerUrl: "/courses/sdet-automation-masterclass.jpg",
    difficultyLevel: "All Levels",
    durationHours: 32,
    priceINR: 5999,
    discountPriceINR: 2499,
    status: "PUBLISHED",
    rating: 4.95,
    ratingsCount: 520,
    studentsCount: 3400,
    updatedAt: "2026-03-10",
    objectives: [
      "Master software test lifecycle (STLC), test strategy, test plan design, and defect management",
      "Perform robust backend and REST API validation using Postman, Swagger, and automated assertions",
      "Execute complex SQL queries and database validation across relational database systems",
      "Build modern end-to-end web test suites with Playwright, TypeScript, and multi-browser execution",
      "Implement trace debugging, network interception, and video recording for zero flaky tests",
      "Configure automated GitHub Actions and Jenkins quality gates for pull request validation",
    ],
    prerequisites: [
      "Basic understanding of computers and web applications — no prior programming required",
    ],
    targetAudience: [
      "Beginners and non-coders wanting to enter the software testing industry with high-demand skills",
      "Manual QA testers looking to expand into Full-Stack SDET automation and API validation",
      "Developers looking to master modern E2E testing best practices",
    ],
    modules: [
      {
        id: "mod-2-1",
        courseId: "course-2",
        title: "Module 01: QA Architecture, Test Strategy & STLC Fundamentals",
        order: 1,
        chapters: [
          {
            id: "chap-2-1",
            moduleId: "mod-2-1",
            title: "Test Design, Risk Analysis & Defect Lifecycle",
            order: 1,
            lessons: [
              {
                id: "les-2-1",
                chapterId: "chap-2-1",
                title: "Software Test Lifecycle (STLC) & Modern Agile QA",
                order: 1,
                durationMinutes: 25,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Complete overview of modern agile test strategies, acceptance criteria, test matrices, and boundary value analysis.",
              },
              {
                id: "les-2-2",
                chapterId: "chap-2-1",
                title: "Defect Management, Root-Cause Analysis & JIRA Workflows",
                order: 2,
                durationMinutes: 30,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Learn how to document high-impact defect reports, severity vs priority triage, and root-cause analysis.",
              },
            ],
          },
        ],
      },
      {
        id: "mod-2-2",
        courseId: "course-2",
        title: "Module 02: API & Database Validation for SDETs",
        order: 2,
        chapters: [
          {
            id: "chap-2-2",
            moduleId: "mod-2-2",
            title: "REST APIs & SQL Data Verification",
            order: 1,
            lessons: [
              {
                id: "les-2-3",
                chapterId: "chap-2-2",
                title: "RESTful Architecture, Status Codes & Postman Testing",
                order: 1,
                durationMinutes: 35,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Master HTTP request verbs, headers, auth tokens, response payload parsing, and automated schema validation.",
              },
              {
                id: "les-2-4",
                chapterId: "chap-2-2",
                title: "SQL Queries, Joins & Database Integrity Verification",
                order: 2,
                durationMinutes: 40,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Learn SQL queries for backend data verification, CRUD validation, table joins, and transactional consistency.",
              },
            ],
          },
        ],
      },
      {
        id: "mod-2-3",
        courseId: "course-2",
        title: "Module 03: Modern E2E Browser Automation with Playwright",
        order: 3,
        chapters: [
          {
            id: "chap-2-3",
            moduleId: "mod-2-3",
            title: "Playwright Architecture & Resilient UI Automation",
            order: 1,
            lessons: [
              {
                id: "les-2-5",
                chapterId: "chap-2-3",
                title: "Playwright Setup, TypeScript Configuration & First Test",
                order: 1,
                durationMinutes: 30,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Configure Playwright with TypeScript, browser drivers, and execute tests across Chromium, Firefox, and WebKit.",
              },
              {
                id: "les-2-6",
                chapterId: "chap-2-3",
                title: "Auto-Waiting, Web-First Assertions & Flake Elimination",
                order: 2,
                durationMinutes: 45,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Leverage Playwright's automatic wait mechanism and locator strategies for zero-flake test execution.",
              },
            ],
          },
        ],
      },
      {
        id: "mod-2-4",
        courseId: "course-2",
        title: "Module 04: CI/CD Quality Gates & Final SDET Assessment",
        order: 4,
        chapters: [
          {
            id: "chap-2-4",
            moduleId: "mod-2-4",
            title: "Continuous Testing & Certification",
            order: 1,
            lessons: [
              {
                id: "les-2-7",
                chapterId: "chap-2-4",
                title: "GitHub Actions CI Pipelines & HTML Report Generation",
                order: 1,
                durationMinutes: 35,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Set up GitHub Actions to trigger automated test suites on pull requests with artifact upload and Slack notifications.",
              },
              {
                id: "les-2-8",
                chapterId: "chap-2-4",
                title: "Assessment: Full-Stack QA & SDET Certification Quiz",
                order: 2,
                durationMinutes: 20,
                type: "quiz",
              },
            ],
          },
        ],
      },
    ],
  },
];

export const INITIAL_QUIZ: Quiz = {
  id: "quiz-1",
  courseId: "course-1",
  title: "Selenium Java + AI Automation Assessment",
  passingPercentage: 70,
  timeLimitMinutes: 10,
  maxAttempts: 3,
  questions: [
    {
      id: "q-1",
      quizId: "quiz-1",
      questionText: "Which W3C standard replaced the legacy JSON Wire Protocol in modern Selenium WebDriver?",
      type: "single_choice",
      options: [
        { id: "opt-1", text: "W3C WebDriver Specification" },
        { id: "opt-2", text: "Chrome DevTools Protocol (CDP)" },
        { id: "opt-3", text: "RESTful HTTP Endpoints v2" },
        { id: "opt-4", text: "gRPC Streaming Driver" },
      ],
      correctAnswer: "opt-1",
      explanation: "Selenium 4 fully adheres to the W3C WebDriver standard, eliminating redundant protocol handshakes.",
    },
    {
      id: "q-2",
      quizId: "quiz-1",
      questionText: "Why is ThreadLocal<WebDriver> recommended in parallel TestNG execution?",
      type: "single_choice",
      options: [
        { id: "opt-1", text: "To isolate WebDriver instances per thread and avoid race conditions" },
        { id: "opt-2", text: "To reduce memory consumption to zero" },
        { id: "opt-3", text: "To automatically restart crashed browsers" },
        { id: "opt-4", text: "To convert tests to headless mode dynamically" },
      ],
      correctAnswer: "opt-1",
      explanation: "ThreadLocal guarantees that each concurrent test thread operates its own isolated browser session without interference.",
    },
    {
      id: "q-3",
      quizId: "quiz-1",
      questionText: "How does AI self-healing locator technology improve test framework resilience?",
      type: "single_choice",
      options: [
        { id: "opt-1", text: "By dynamically identifying alternate element attributes when DOM IDs change" },
        { id: "opt-2", text: "By bypassing user authentication completely" },
        { id: "opt-3", text: "By eliminating the need to write assertions" },
        { id: "opt-4", text: "By automatically fixing server-side bugs" },
      ],
      correctAnswer: "opt-1",
      explanation: "AI self-healing locators analyze historical DOM tree snapshots and weighted attributes (text, position, hierarchy) to resolve modified elements automatically.",
    },
    {
      id: "q-4",
      quizId: "quiz-1",
      questionText: "True or False: Implicit Wait and Explicit Wait should NEVER be mixed in the same WebDriver instance.",
      type: "true_false",
      options: [
        { id: "opt-1", text: "True" },
        { id: "opt-2", text: "False" },
      ],
      correctAnswer: "opt-1",
      explanation: "Mixing implicit and explicit waits causes unpredictable wait times because the timeout calculations compound unpredictably in the driver.",
    },
  ],
};

export const INITIAL_LIVE_SESSIONS: LiveSession[] = [
  {
    id: "live-1",
    title: "Selenium Java + AI: Live Self-Healing Framework Masterclass",
    instructorName: "Rahul Kamat",
    date: "2026-03-25",
    startTime: "19:00 IST",
    endTime: "21:00 IST",
    capacity: 250,
    meetingUrl: "https://meet.ngta.in/sdet-arch-live",
    status: "UPCOMING",
  },
  {
    id: "live-2",
    title: "CI/CD Test Pipelines with Jenkins & Docker: Live Lab",
    instructorName: "Rahul Kamat",
    date: "2026-03-29",
    startTime: "18:00 IST",
    endTime: "20:00 IST",
    capacity: 180,
    meetingUrl: "https://meet.ngta.in/cicd-qa-lab",
    status: "UPCOMING",
  },
];

export const INITIAL_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "post-1",
    channelId: "general-qa",
    authorName: "Karan Johar",
    authorRole: "LEARNER",
    content: "Just migrated our entire regression suite to ThreadLocal parallel execution in TestNG as taught in Module 03. Execution time dropped from 4 hours to 35 minutes! Kudos to Rahul sir!",
    createdAt: "2 hours ago",
    reactions: [{ emoji: "🔥", count: 14 }, { emoji: "🚀", count: 8 }],
    repliesCount: 4,
  },
  {
    id: "post-2",
    channelId: "code-review",
    authorName: "Rahul Kamat",
    authorRole: "INSTRUCTOR",
    authorAvatar: "/instructor/rahul-kamat.png",
    content: "Weekly Code Challenge: Implement an AI self-healing fallback locator for dynamic data tables without hardcoded XPath indexes. Best implementation earns 100 Reputation points!",
    createdAt: "5 hours ago",
    reactions: [{ emoji: "💡", count: 22 }],
    repliesCount: 11,
  },
];
