import { Course, Quiz, Certificate, LiveSession, CommunityPost } from "@/types";

export const INITIAL_COURSES: Course[] = [
  {
    id: "course-1",
    slug: "selenium-automation-masterclass",
    title: "Selenium WebDriver & Test Automation Framework Architecture",
    subtitle: "Enterprise-grade UI testing with Java, TestNG, Page Object Model, and CI/CD pipelines",
    description: "Master industry-standard automation testing from foundational WebDriver architecture to scalable enterprise test frameworks with Docker, Jenkins, and reporting dashboards.",
    instructorId: "inst-1",
    instructorName: "Vikram Malhotra",
    instructorTitle: "Lead SDET @ FinTech Global",
    category: "Automation Testing",
    tags: ["Selenium", "Java", "TestNG", "CI/CD", "Framework Design"],
    thumbnailUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=60",
    bannerUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1400&auto=format&fit=crop&q=80",
    difficultyLevel: "Intermediate",
    durationHours: 28,
    priceINR: 4999,
    discountPriceINR: 2499,
    status: "PUBLISHED",
    rating: 4.9,
    ratingsCount: 342,
    studentsCount: 1820,
    updatedAt: "2026-03-01",
    objectives: [
      "Architect a robust Data-Driven & Hybrid Automation Framework from scratch",
      "Implement dynamic synchronization, Page Factory, and robust locator strategies",
      "Integrate Selenium Grid execution in parallel via Docker containers",
      "Generate rich Extent and Allure reports with automated screenshot capture on failure",
    ],
    prerequisites: [
      "Basic understanding of Core Java (OOP concepts)",
      "Familiarity with manual software testing methodologies",
    ],
    targetAudience: [
      "Manual QA engineers transitioning to SDET roles",
      "Automation testers seeking framework architecture mastery",
    ],
    modules: [
      {
        id: "mod-1",
        courseId: "course-1",
        title: "Module 01: Core Architecture & Locator Strategies",
        order: 1,
        chapters: [
          {
            id: "chap-1-1",
            moduleId: "mod-1",
            title: "WebDriver Architecture Deep Dive",
            order: 1,
            lessons: [
              {
                id: "les-1",
                chapterId: "chap-1-1",
                title: "Introduction to W3C WebDriver Protocol",
                order: 1,
                durationMinutes: 18,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "In this lesson, we break down the client-server communication mechanism between Language Bindings, JSON Wire Protocol, and W3C standard drivers.",
              },
              {
                id: "les-2",
                chapterId: "chap-1-1",
                title: "Mastering XPath Axes & CSS Selectors",
                order: 2,
                durationMinutes: 24,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Comprehensive guide to writing resilient XPath queries using following-sibling, ancestor, parent, and dynamic regex matching.",
              },
            ],
          },
        ],
      },
      {
        id: "mod-2",
        courseId: "course-1",
        title: "Module 02: Framework Construction & Reporting",
        order: 2,
        chapters: [
          {
            id: "chap-2-1",
            moduleId: "mod-2",
            title: "TestNG & Parallel Execution",
            order: 1,
            lessons: [
              {
                id: "les-3",
                chapterId: "chap-2-1",
                title: "Configuring ThreadLocal WebDriver for Thread Safety",
                order: 1,
                durationMinutes: 32,
                type: "video",
                videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
                content: "Prevent race conditions during multi-browser parallel execution with Java ThreadLocal.",
              },
              {
                id: "les-4",
                chapterId: "chap-2-1",
                title: "Assessment: Framework Mastery Quiz",
                order: 2,
                durationMinutes: 15,
                type: "quiz",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "course-2",
    slug: "playwright-typescript-end-to-end",
    title: "NextGen E2E Testing with Playwright & TypeScript",
    subtitle: "Modern auto-waiting, network mocking, trace viewer, and GitHub Actions CI pipelines",
    description: "Fast, reliable, cross-browser web testing for modern web applications using Microsoft Playwright.",
    instructorId: "inst-2",
    instructorName: "Ananya Sharma",
    instructorTitle: "Principal Test Architect",
    category: "Modern Web Testing",
    tags: ["Playwright", "TypeScript", "E2E", "CI/CD"],
    thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=60",
    bannerUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&auto=format&fit=crop&q=80",
    difficultyLevel: "Advanced",
    durationHours: 20,
    priceINR: 5999,
    discountPriceINR: 2999,
    status: "PUBLISHED",
    rating: 4.95,
    ratingsCount: 210,
    studentsCount: 940,
    updatedAt: "2026-03-10",
    objectives: [
      "Master Playwright execution engine and native multi-context isolation",
      "Intercept and mock network traffic for backend-independent UI testing",
      "Analyze flaky tests with Playwright Trace Viewer and video recording",
    ],
    prerequisites: ["Familiarity with JavaScript/TypeScript fundamentals"],
    targetAudience: ["QA Engineers, Frontend Developers, SDETs"],
    modules: [],
  },
];

export const INITIAL_QUIZ: Quiz = {
  id: "quiz-1",
  courseId: "course-1",
  title: "Selenium Framework Architecture & Protocol Assessment",
  passingPercentage: 70,
  timeLimitMinutes: 10,
  maxAttempts: 3,
  questions: [
    {
      id: "q-1",
      quizId: "quiz-1",
      questionText: "Which W3C standard replaced the legacy JSON Wire Protocol in modern Selenium WebDriver?",
      type: "single_choice",
      options: [
        { id: "opt-1", text: "W3C WebDriver Specification" },
        { id: "opt-2", text: "Chrome DevTools Protocol (CDP)" },
        { id: "opt-3", text: "RESTful HTTP Endpoints v2" },
        { id: "opt-4", text: "gRPC Streaming Driver" },
      ],
      correctAnswer: "opt-1",
      explanation: "Selenium 4 fully adheres to the W3C WebDriver standard, eliminating redundant protocol handshakes.",
    },
    {
      id: "q-2",
      quizId: "quiz-1",
      questionText: "Why is ThreadLocal<WebDriver> recommended in parallel TestNG execution?",
      type: "single_choice",
      options: [
        { id: "opt-1", text: "To isolate WebDriver instances per thread and avoid race conditions" },
        { id: "opt-2", text: "To reduce memory consumption to zero" },
        { id: "opt-3", text: "To automatically restart crashed browsers" },
        { id: "opt-4", text: "To convert tests to headless mode dynamically" },
      ],
      correctAnswer: "opt-1",
      explanation: "ThreadLocal guarantees that each concurrent test thread operates its own isolated browser session without interference.",
    },
    {
      id: "q-3",
      quizId: "quiz-1",
      questionText: "True or False: Implicit Wait and Explicit Wait should NEVER be mixed in the same WebDriver instance.",
      type: "true_false",
      options: [
        { id: "opt-1", text: "True" },
        { id: "opt-2", text: "False" },
      ],
      correctAnswer: "opt-1",
      explanation: "Mixing implicit and explicit waits causes unpredictable wait times because the timeout calculations compound unpredictably in the driver.",
    },
  ],
};

export const INITIAL_LIVE_SESSIONS: LiveSession[] = [
  {
    id: "live-1",
    title: "Mastering Test Architecture: Live SDET Workshop",
    instructorName: "Vikram Malhotra",
    date: "2026-03-25",
    startTime: "19:00 IST",
    endTime: "21:00 IST",
    capacity: 250,
    meetingUrl: "https://meet.ngta.in/sdet-arch-live",
    status: "UPCOMING",
  },
  {
    id: "live-2",
    title: "CI/CD Pipelines for QA: Live Hands-on Lab",
    instructorName: "Ananya Sharma",
    date: "2026-03-29",
    startTime: "18:00 IST",
    endTime: "20:00 IST",
    capacity: 180,
    meetingUrl: "https://meet.ngta.in/cicd-qa-lab",
    status: "UPCOMING",
  },
];

export const INITIAL_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "post-1",
    channelId: "general-qa",
    authorName: "Karan Johar",
    authorRole: "LEARNER",
    content: "Just migrated our entire regression suite to ThreadLocal parallel execution in TestNG. Execution time dropped from 4 hours to 35 minutes! Kudos to Module 02.",
    createdAt: "2 hours ago",
    reactions: [{ emoji: "🔥", count: 14 }, { emoji: "🚀", count: 8 }],
    repliesCount: 4,
  },
  {
    id: "post-2",
    channelId: "code-review",
    authorName: "Vikram Malhotra",
    authorRole: "INSTRUCTOR",
    content: "Weekly Code Challenge: Optimize your dynamic table locators without using hardcoded index numbers. Best submission gets 100 Gamification points!",
    createdAt: "5 hours ago",
    reactions: [{ emoji: "💡", count: 22 }],
    repliesCount: 11,
  },
];
